### ISSUE TITLE
How to use an open source solver instead of Knitro

### ISSUE THREAD

**Issue by tcjcxy30** [changliuliu/CFS#1]
Hi：
     I don't have  Knitro license, so I want to replace it with an open source solver. Which solver can I use? What do I need to modify? Thank you.

**Comment by changliuliu** [comment]
Our current C++ implementation heavily depends on Knitro's template. It may not be trivial to switch to another solver. But we will try to release a C++ implementation that does not depend on external solvers.

**Comment by tcjcxy30** [comment]
That sounds great. So when will it be released?

**Comment by changliuliu** [comment]
May not be sometime soon. But we are targeting this summer!

**Comment by Vlanes** [comment]
hi，how's it going~
